# Generated by Django 4.1.3 on 2022-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='user_type',
            field=models.CharField(choices=[('Librarian', 'Librarian'), ('Reader', 'Reader')], max_length=10),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
