# Generated by Django 4.1.3 on 2022-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_libraryuser_email_alter_libraryuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='card_number',
            field=models.CharField(max_length=150, unique=True, verbose_name='card number'),
        ),
    ]
